spring:
  application:
    name: Employee-Assessment-REST-Service
  datasource:
    url: jdbc:postgresql://localhost or ip address with db port number/db name
    username: db - user name
    password: db - password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2   #Connection pool size depends on your requirement
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      
server:
  port: 8081
  servlet:
    context-path: /eas/api/v1
  

 
        
resilience4j:      
  ratelimiter:
    instances:
      employeeRateLimiter:
        limit-refresh-period: 10s
        limit-for-period: 1
        timeout-duration: 5s    
      
      
info:
  app:
    name: Employee Service
    version: 1.0.0
    description: This service only serve employee information
    
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  ExceptionHandlerExceptionResolver: ERROR

      

      
      
     